# This file is part of CMake-easytest.
#
# Copyright (c) 2017 RWTH Aachen University, Federal Republic of Germany
#
# See the LICENSE file in the package base directory for details
#
# Written by Alexander Haase, alexander.haase@rwth-aachen.de
#

language: c
compiler: gcc

os: linux
dist: trusty
sudo: false

script:
  - mkdir travis && cd travis
  - cmake .. && make all && ctest --output-on-failure
